Write and sign metadata
statisticsnorway/dapla-catalog pull request #15
Opened 2020-08-19 20:41 UTC by fnh-ssb

2020-08-20 22:57 UTC, fnh-ssb commented
wait for the helidon testing update

2020-08-26 09:35 UTC, bjornandre approved these changes
Looks good

2020-08-26 09:47 UTC, fnh-ssb commented
waiting for some configuration changes in local stack before merging this pull request.

2020-08-26 20:49 UTC, fnh-ssb commented
this can not be merged until after the pull request in local stack merged.

2020-08-27 05:46 UTC, kimcs requested changes
The names and terms "catalog-verifier" or "catalog-signer" are not accurate. The data that we receive are "metadata" and are the same metadata that is seen elsewhere in dapla. So the term "metadata-verifier" or "metadata-signer" is much better. It's not needed to prefix the verifier or signer with "catalog", in-fact, as these classes are the same as the signer and verifier classes of metadata-distributor and/or data-access, they could be put into a small separate library later on. So consider using the term "metadata" instead of "catalog" for all these related classes and interfaces.

2020-08-27 05:46 UTC, kimcs commented on src/main/java/no/ssb/dapla/catalog/CatalogApplication.java
> +                .register("/catalog", new CatalogHttpService(repository, catalogSignatureVerifier, authService))
authService is not needed and not wanted here.

2020-08-27 05:46 UTC, kimcs commented on src/main/java/no/ssb/dapla/catalog/dataset/CatalogHttpService.java
> +                AccessCheckRequest checkRequest = AccessCheckRequest.newBuilder()
The whole point of the signature verification is to avoid the access-check. Metadata that has been signed is by definition valid and can be written directly to the database. Please remove the external calls to authService from this method.

2020-08-27 05:46 UTC, kimcs commented on src/main/java/no/ssb/dapla/catalog/dataset/CatalogHttpService.java
> +                            repository.create(dataset)
You may write the repository like this without asking authService for permission

2020-08-27 05:46 UTC, kimcs commented on src/test/java/no/ssb/dapla/catalog/dataset/CatalogHttpServiceTest.java
> +@GrpcMockRegistryConfig(DataAccessGrpcMockRegistry.class)
no need for this mock

2020-08-27 05:46 UTC, kimcs commented on src/test/java/no/ssb/dapla/catalog/dataset/DataAccessGrpcMockRegistry.java
> +public class DataAccessGrpcMockRegistry extends GrpcMockRegistry {
remove class

2020-08-27 08:42 UTC, fnh-ssb commented
all done. if you approve, I will merge.

2020-08-27 10:42 UTC, kimcs approved these changes

2020-08-27 10:44 UTC, merged